### ISSUE TITLE
UR Isaac driver for newest Isaac SDK version

### ISSUE THREAD

**Issue by ChrwagnerTHU** [UniversalRobots/Universal_Robots_Isaac_Driver#8]
Hi,
I am trying to control a UR5 using Isaac SIM as part of a university project. Unfortunately, the driver is not suitable for the latest version of Isaac SDK. 
Is there a workaround for this or can an adaptation of the driver be expected in the near future?
Thanks in advance.

**Comment by urmahp** [comment]
Thanks for reporting this. What version of Isaac SDK are you referring to 2021.1? Currently this driver supports version 2020.2, but it should also be working with 2021.1. 

Can you provide any additional information, such as build logs and/or try to describe what issues you have when using the newest Isaac SDK version with this driver?

**Comment by ChrwagnerTHU** [comment]
First of all thank you very much for the quick answer.
I am using SDK version 2021.1 on Ubuntu 20.04.4.
Unfortunately Nvidia does not allow to load older versions of the SDK.

The error occurs as soon as I try to build the first sample application from the repository.

![errorBazel](https://user-images.githubusercontent.com/63110224/182336073-65e644a1-2f76-4450-8b7e-49dcc76b662f.png)

The error message occurs several times for all packages. The screenshot only shows the last lines of the console output.
Could the problem be that many packages used by the application are not available on Ubuntu 20 such as the libvpx5 package?

**Comment by urmahp** [comment]
The issue most likely has something to do with your setup and not with this driver, because Isaac SDK is build for ubuntu 18.04 and does not compile on ubuntu 20.04, see image
![image](https://user-images.githubusercontent.com/79145214/182360301-36c598a7-80d9-4b83-a615-00925e855f28.png)

To verify that it is an issue with your setup you can try to compile any of the packages in Isaac SDK, you can find some examples [here](https://docs.nvidia.com/isaac/doc/getting_started.html). 

Since you are using ubuntu 20.04 I suggest that you run Isaac SDK in a docker container instead of on your local machine, they have some documentation on it [here](https://docs.nvidia.com/isaac/doc/getting_started.html#using-docker).

**Comment by ChrwagnerTHU** [comment]
Thank you very much for your help!
I could solve it by using a docker container as you suggested.
